package com.lyloou.demo.mybatislombok.pojo;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.id
     *
     * @mbg.generated Wed Feb 20 18:00:03 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_name
     *
     * @mbg.generated Wed Feb 20 18:00:03 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.password
     *
     * @mbg.generated Wed Feb 20 18:00:03 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.age
     *
     * @mbg.generated Wed Feb 20 18:00:03 CST 2019
     */
    private Integer age;
}